In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# -------- CUSTOMERS --------
n_customers = 5000
customers = pd.DataFrame({
    "Customer_ID": [f"C{str(i).zfill(4)}" for i in range(n_customers)],
    "Customer_Name": np.random.choice(
        ["John Doe", "jane doe", "J. Smith", "Alice", "bob", None],
        n_customers
    ),
    "Region": np.random.choice(
        ["North", "south", "EAST", "west", "West.", None],
        n_customers
    ),
    "Signup_Date": np.random.choice(
        pd.date_range("2020-01-01", "2023-12-31"),
        n_customers
    )
})

# -------- PRODUCTS --------
n_products = 500
products = pd.DataFrame({
    "Product_ID": [f"P{str(i).zfill(4)}" for i in range(n_products)],
    "Product_Name": np.random.choice(
        ["Laptop", "phone", "Chair", "Desk", "Tablet", None],
        n_products
    ),
    "Category": np.random.choice(
        ["Tech", "tech", "FURN", "Furniture", None],
        n_products
    ),
    "Cost_Price": np.random.uniform(50, 500, n_products),
    "Selling_Price": np.random.uniform(100, 1000, n_products)
})

# introduce bad pricing
products.loc[np.random.choice(products.index, 20), "Cost_Price"] = 900

# -------- ORDERS --------
n_orders = 60000
orders = pd.DataFrame({
    "Order_ID": np.random.choice([f"O{str(i).zfill(5)}" for i in range(n_orders//2)], n_orders),
    "Customer_ID": np.random.choice(customers["Customer_ID"].tolist() + [None], n_orders),
    "Product_ID": np.random.choice(products["Product_ID"].tolist(), n_orders),
    "Order_Date": np.random.choice(
        ["2023-01-01", "01/02/2023", "March 5 2023"],
        n_orders
    ),
    "Quantity": np.random.randint(1, 10, n_orders),
    "Discount": np.random.uniform(-0.2, 1.5, n_orders)
})

# -------- PAYMENTS --------
payments = pd.DataFrame({
    "Payment_ID": [f"PAY{str(i).zfill(5)}" for i in range(n_orders)],
    "Order_ID": np.random.choice(orders["Order_ID"], n_orders),
    "Payment_Method": np.random.choice(["Card", "Cash", "Transfer"], n_orders),
    "Payment_Status": np.random.choice(["Paid", "Pending", "Failed"], n_orders)
})

# -------- SAVE FILES --------
customers.to_csv("customers_brutal.csv", index=False)
products.to_csv("products_brutal.csv", index=False)
orders.to_csv("orders_brutal.csv", index=False)
payments.to_csv("payments_brutal.csv", index=False)

print("Brutal dataset created!")

Brutal dataset created!

In [2]:
import pandas as pd

customers = pd.read_csv("C:/Users/JAMES/Desktop/Data Science/brutal/customers_brutal.csv")
products = pd.read_csv("C:/Users/JAMES/Desktop/Data Science/brutal/products_brutal.csv")
orders = pd.read_csv("C:/Users/JAMES/Desktop/Data Science/brutal/orders_brutal.csv")
payments = pd.read_csv("C:/Users/JAMES/Desktop/Data Science/brutal/payments_brutal.csv")

In [3]:
customers.info()
customers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5000 non-null   object
 1   Customer_Name  4179 non-null   object
 2   Region         4164 non-null   object
 3   Signup_Date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

  Customer_ID Customer_Name Region Signup_Date
0       C0000         Alice   west  2021-08-22
1       C0001           bob  North  2021-05-28
2       C0002      J. Smith   west  2020-03-24
3       C0003           bob   west  2022-09-20
4       C0004           bob   west  2022-12-02

In [4]:
products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     500 non-null    object
 1   Product_Name   410 non-null    object
 2   Category       400 non-null    object
 3   Cost_Price     500 non-null    float64
 4   Selling_Price  500 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

  Product_ID Product_Name Category  Cost_Price  Selling_Price
0      P0000          NaN      NaN  343.093954     475.037797
1      P0001        phone     Tech  141.107983     165.486139
2      P0002        Chair     tech  450.551811     188.892146
3      P0003        phone     Tech  436.570848     474.324880
4      P0004         Desk      NaN   84.527317     374.843334

In [5]:
orders.info()
orders.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     60000 non-null  object
 1   Customer_ID  59982 non-null  object
 2   Product_ID   60000 non-null  object
 3   Order_Date   60000 non-null  object
 4   Quantity     60000 non-null  int64
 5   Discount     60000 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.7+ MB

  Order_ID Customer_ID Product_ID    Order_Date  Quantity  Discount
0   O26710       C4798      P0235    01/02/2023         2  1.179807
1   O13492       C2575      P0426    01/02/2023         7  0.951665
2   O13336       C3374      P0248    2023-01-01         5  0.495850
3   O24509       C4792      P0035    2023-01-01         5  0.750614
4   O19843       C3713      P0112  March 5 2023         2  0.062022

In [6]:
payments.info()
payments.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      60000 non-null  object
 1   Order_ID        60000 non-null  object
 2   Payment_Method  60000 non-null  object
 3   Payment_Status  60000 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB

  Payment_ID Order_ID Payment_Method Payment_Status
0   PAY00000   O12564           Card        Pending
1   PAY00001   O22447           Card        Pending
2   PAY00002   O25476           Cash         Failed
3   PAY00003   O27856           Card         Failed
4   PAY00004   O19202           Cash           Paid

In [7]:
customers.isnull().sum()

Customer_ID        0
Customer_Name    821
Region           836
Signup_Date        0
dtype: int64

In [8]:
products.isnull().sum()

Product_ID         0
Product_Name      90
Category         100
Cost_Price         0
Selling_Price      0
dtype: int64

In [9]:
orders.isnull().sum()

Order_ID        0
Customer_ID    18
Product_ID      0
Order_Date      0
Quantity        0
Discount        0
dtype: int64

In [10]:

payments.isnull().sum()

Payment_ID        0
Order_ID          0
Payment_Method    0
Payment_Status    0
dtype: int64

In [11]:
customers['Customer_ID'].nunique(), len(customers)

(5000, 5000)

In [12]:
products['Product_ID'].nunique(), len(products)

(500, 500)

In [13]:
orders['Order_ID'].nunique(), len(orders)

(25959, 60000)

In [14]:
payments['Payment_ID'].nunique(), len(payments)

(60000, 60000)

In [15]:
orders['Customer_ID'].isin(customers['Customer_ID']).value_counts()

Customer_ID
True     59982
False       18
Name: count, dtype: int64

In [16]:
orders[~orders['Customer_ID'].isin(customers['Customer_ID'])]

      Order_ID Customer_ID Product_ID    Order_Date  Quantity  Discount
4538    O14887         NaN      P0181  March 5 2023         4  0.525871
5467    O23585         NaN      P0075    01/02/2023         8  0.199705
5747    O08633         NaN      P0479    2023-01-01         7  0.770556
10107   O18128         NaN      P0295  March 5 2023         1  1.460918
12092   O25390         NaN      P0103    01/02/2023         8  0.352384
12291   O19501         NaN      P0425  March 5 2023         2  0.794372
18663   O13896         NaN      P0421  March 5 2023         2  1.489568
22286   O07403         NaN      P0259  March 5 2023         3  0.543913
24907   O25309         NaN      P0301    01/02/2023         9  0.066057
25477   O18836         NaN      P0365    01/02/2023         1  1.402631
32241   O15389         NaN      P0126    01/02/2023         4  0.621099
35218   O09237         NaN      P0159    2023-01-01         1 -0.008791
38133   O29763         NaN      P0052    01/02/2023         2 -0.113933
38588   O18167         NaN      P0155    2023-01-01         6  1.106007
45379   O25793         NaN      P0332    01/02/2023         7  0.805849
49492   O10386         NaN      P0453    2023-01-01         6  1.257834
51397   O01133         NaN      P0013    01/02/2023         4 -0.085084
53556   O27333         NaN      P0194    2023-01-01         7  0.859233

In [17]:
orders['Product_ID'].isin(products['Product_ID']).value_counts()

Product_ID
True    60000
Name: count, dtype: int64

In [18]:
payments['Order_ID'].isin(payments['Order_ID']).value_counts()

Order_ID
True    60000
Name: count, dtype: int64

In [19]:
orders['Discount'].describe()

count    60000.000000
mean         0.650921
std          0.491359
min         -0.199964
25%          0.224810
50%          0.653081
75%          1.075621
max          1.499951
Name: Discount, dtype: float64

In [20]:
(products['Cost_Price'] > products['Selling_Price']).sum()

np.int64(100)

In [21]:
orders['Order_Date'].head(20)

0       01/02/2023
1       01/02/2023
2       2023-01-01
3       2023-01-01
4     March 5 2023
5       2023-01-01
6     March 5 2023
7     March 5 2023
8     March 5 2023
9       01/02/2023
10      2023-01-01
11      01/02/2023
12      01/02/2023
13    March 5 2023
14      2023-01-01
15      01/02/2023
16    March 5 2023
17      2023-01-01
18      01/02/2023
19      01/02/2023
Name: Order_Date, dtype: object

In [22]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     500 non-null    object
 1   Product_Name   410 non-null    object
 2   Category       400 non-null    object
 3   Cost_Price     500 non-null    float64
 4   Selling_Price  500 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

In [23]:
products.head()

  Product_ID Product_Name Category  Cost_Price  Selling_Price
0      P0000          NaN      NaN  343.093954     475.037797
1      P0001        phone     Tech  141.107983     165.486139
2      P0002        Chair     tech  450.551811     188.892146
3      P0003        phone     Tech  436.570848     474.324880
4      P0004         Desk      NaN   84.527317     374.843334

In [24]:
customers_clean = customers.copy()

In [25]:

products_clean = products.copy()

In [26]:

orders_clean = orders.copy()

In [27]:

payments_clean = payments.copy()

In [28]:
customers_clean['Customer_Name'] = customers_clean['Customer_Name'].fillna('Unknown')

In [29]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5000 non-null   object
 1   Customer_Name  5000 non-null   object
 2   Region         4164 non-null   object
 3   Signup_Date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [30]:
customers_clean['Region'] = customers_clean['Region'].str.strip().str.lower()

customers_clean['Region'] = customers_clean['Region'].replace({
    'west':'west',
    'east':'east',
    'north':'north',
    'west':'west'
})

customers_clean['Region'] = customers['Region'].str.title()

customers_clean['Region'] = customers_clean['Region'].fillna('Unknown')

In [31]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5000 non-null   object
 1   Customer_Name  5000 non-null   object
 2   Region         5000 non-null   object
 3   Signup_Date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [32]:
customers_clean['Signup_Date'] =pd.to_datetime(customers_clean['Signup_Date'], errors='coerce')

In [33]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5000 non-null   object
 1   Customer_Name  5000 non-null   object
 2   Region         5000 non-null   object
 3   Signup_Date    5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 156.4+ KB

In [34]:
customers_clean['Customer_Name'].value_counts().head()
customers_clean['Region'].value_counts()

Region
South      889
West.      837
Unknown    836
West       830
East       813
North      795
Name: count, dtype: int64

In [35]:
products_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     500 non-null    object
 1   Product_Name   410 non-null    object
 2   Category       400 non-null    object
 3   Cost_Price     500 non-null    float64
 4   Selling_Price  500 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

In [36]:
products_clean = products_clean.dropna(subset=['Product_Name'])

In [37]:
products_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 410 entries, 1 to 498
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     410 non-null    object
 1   Product_Name   410 non-null    object
 2   Category       328 non-null    object
 3   Cost_Price     410 non-null    float64
 4   Selling_Price  410 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.2+ KB

In [38]:
products_clean['Category'] = products_clean['Category'].str.strip().str.lower()

products_clean['Category'] = products_clean['Category']. replace({
    'tech':'technology',
    'furn':'furniture'
})

products_clean['Category'] = products_clean['Category'].str.title()

products_clean['Category'] = products_clean['Category'].fillna('Unknown')

In [39]:
products_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 410 entries, 1 to 498
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     410 non-null    object
 1   Product_Name   410 non-null    object
 2   Category       410 non-null    object
 3   Cost_Price     410 non-null    float64
 4   Selling_Price  410 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.2+ KB

In [40]:
products_clean = products_clean[products_clean['Cost_Price'] <= products_clean['Selling_Price']]

In [41]:
products_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 328 entries, 1 to 497
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     328 non-null    object
 1   Product_Name   328 non-null    object
 2   Category       328 non-null    object
 3   Cost_Price     328 non-null    float64
 4   Selling_Price  328 non-null    float64
dtypes: float64(2), object(3)
memory usage: 15.4+ KB

In [42]:
len(products_clean)

328

In [43]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     60000 non-null  object
 1   Customer_ID  59982 non-null  object
 2   Product_ID   60000 non-null  object
 3   Order_Date   60000 non-null  object
 4   Quantity     60000 non-null  int64
 5   Discount     60000 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.7+ MB

In [44]:
orders_clean = orders_clean[orders_clean['Customer_ID'].isin(customers_clean['Customer_ID'])]

In [45]:
orders_clean['Order_Date'] =pd.to_datetime(orders_clean['Order_Date'], errors='coerce')

In [46]:
orders_clean = orders_clean[(orders_clean['Discount'] >=0 ) & (orders_clean['Discount'] <=1)]

In [47]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35183 entries, 1 to 59998
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     35183 non-null  object
 1   Customer_ID  35183 non-null  object
 2   Product_ID   35183 non-null  object
 3   Order_Date   11883 non-null  datetime64[ns]
 4   Quantity     35183 non-null  int64
 5   Discount     35183 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 1.9+ MB

In [48]:
orders_clean = orders_clean[orders_clean['Product_ID'].isin(products_clean['Product_ID'])]

In [49]:
payments_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      60000 non-null  object
 1   Order_ID        60000 non-null  object
 2   Payment_Method  60000 non-null  object
 3   Payment_Status  60000 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB

In [50]:
payments_clean = payments_clean[payments_clean['Order_ID'].isin(orders_clean['Order_ID'])]

In [51]:
payments_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42986 entries, 1 to 59998
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      42986 non-null  object
 1   Order_ID        42986 non-null  object
 2   Payment_Method  42986 non-null  object
 3   Payment_Status  42986 non-null  object
dtypes: object(4)
memory usage: 1.6+ MB

In [52]:
customers_clean.isnull().sum()
products_clean.isnull().sum()
orders_clean.isnull().sum()
payments_clean.isnull().sum()

Payment_ID        0
Order_ID          0
Payment_Method    0
Payment_Status    0
dtype: int64

In [53]:
orders_clean['Customer_ID'].isin(customers_clean['Customer_ID']).value_counts()

Customer_ID
True    23131
Name: count, dtype: int64

In [54]:
orders_clean['Product_ID'].isin(products_clean['Product_ID']).value_counts()

Product_ID
True    23131
Name: count, dtype: int64

In [55]:
payments_clean['Order_ID'].isin(orders_clean['Order_ID']).value_counts()

Order_ID
True    42986
Name: count, dtype: int64

In [56]:
customers_clean.to_csv("customers_clean.csv", index=False)

In [57]:
products_clean.to_csv("products_clean.csv", index=False)

In [58]:
orders_clean.to_csv("orders_clean.csv", index=False)

In [59]:
payments_clean.to_csv("payments_clean.csv", index=False)

In [60]:
orders_header = orders_clean[['Order_ID', 'Customer_ID', 'Order_Date']].drop_duplicates()

In [61]:
orders_clean.to_csv("orders_clean.csv", index=False)

In [62]:
orders_header.to_csv("orders_header.csv", index=False)

In [63]:
orders_header['Order_ID'].nunique(), len(orders_header)

(16114, 23131)

In [64]:
orders_header = orders_clean[['Order_ID', 'Customer_ID', 'Order_Date']].drop_duplicates()

In [65]:
orders_header['Order_ID'].nunique(), len(orders_header)

(16114, 23131)

In [66]:
orders_header = orders_clean.drop_duplicates(subset=['Order_ID'])

In [67]:
orders_header['Order_ID'].nunique(), len(orders_header)

(16114, 16114)

In [68]:
orders_header['Order_ID'].isnull().sum()

np.int64(0)

In [69]:
orders_header = orders_header.dropna(subset=['Order_ID'])

In [70]:
orders_header.to_csv("orders_header.csv", index=False)

In [71]:
orders_clean['Order_ID'].is_unique

False

orders_clean["Order_ID"].duplicated().sum()

In [72]:
orders_clean["Order_ID"].duplicated().sum()

np.int64(7017)

In [73]:
orders_clean[orders_clean["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

      Order_ID Customer_ID Product_ID Order_Date  Quantity  Discount
45098   O00000       C1228      P0156 2023-01-02         4  0.383447
38500   O00000       C1656      P0330 2023-01-02         4  0.672115
46059   O00003       C4690      P0337        NaT         9  0.352961
8651    O00003       C3045      P0301 2023-01-02         9  0.647904
32622   O00011       C0364      P0236 2023-01-02         1  0.883727
...        ...         ...        ...        ...       ...       ...
2413    O29997       C3346      P0183        NaT         3  0.975307
2536    O29997       C3691      P0360        NaT         1  0.598544
32701   O29997       C3839      P0283        NaT         3  0.201943
30672   O29998       C2375      P0114 2023-01-02         9  0.782567
52066   O29998       C4890      P0445 2023-01-02         7  0.408373

[12453 rows x 6 columns]

In [74]:
payments_clean["Order_ID"].duplicated().sum()

payments_clean[payments_clean["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

      Payment_ID Order_ID Payment_Method Payment_Status
52081   PAY52081   O00000           Card           Paid
4935    PAY04935   O00000           Card         Failed
59966   PAY59966   O00000       Transfer         Failed
15381   PAY15381   O00002           Card        Pending
20913   PAY20913   O00002           Card        Pending
...          ...      ...            ...            ...
49274   PAY49274   O29997       Transfer         Failed
28341   PAY28341   O29997           Cash         Failed
37112   PAY37112   O29997           Card         Failed
56981   PAY56981   O29998           Card         Failed
48244   PAY48244   O29998           Cash           Paid

[39636 rows x 4 columns]

In [75]:
orders_clean["Order_ID"].value_counts().head(10)

Order_ID
O26989    6
O04925    6
O15735    6
O01961    5
O08330    5
O11961    5
O26543    5
O14659    5
O24603    5
O16881    5
Name: count, dtype: int64

In [76]:
orders_clean = orders_clean.drop_duplicates(subset=["Order_ID"])

In [77]:
# Check if Order_ID is unique
orders_clean["Order_ID"].is_unique

True

In [78]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16114 entries, 3 to 59997
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     16114 non-null  object
 1   Customer_ID  16114 non-null  object
 2   Product_ID   16114 non-null  object
 3   Order_Date   5416 non-null   datetime64[ns]
 4   Quantity     16114 non-null  int64
 5   Discount     16114 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 881.2+ KB

In [79]:
orders_clean = pd.read_csv("C:/Users/JAMES/Desktop/Data Science/brutal/cleaned/orders_clean.csv")

In [80]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23131 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     23131 non-null  object
 1   Customer_ID  23131 non-null  object
 2   Product_ID   23131 non-null  object
 3   Order_Date   7795 non-null   object
 4   Quantity     23131 non-null  int64
 5   Discount     23131 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB

In [81]:
dim_orders = orders_clean.drop_duplicates(subset=["Order_ID"])

In [82]:
dim_orders["Order_ID"].is_unique

True

In [83]:
dim_orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16114 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     16114 non-null  object
 1   Customer_ID  16114 non-null  object
 2   Product_ID   16114 non-null  object
 3   Order_Date   5416 non-null   object
 4   Quantity     16114 non-null  int64
 5   Discount     16114 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 881.2+ KB

In [84]:
dim_orders.to_csv("dim_orders.csv", index=False)

In [85]:
orders_clean.to_csv("orders_clean.csv", index=False)

In [86]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23131 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     23131 non-null  object
 1   Customer_ID  23131 non-null  object
 2   Product_ID   23131 non-null  object
 3   Order_Date   7795 non-null   object
 4   Quantity     23131 non-null  int64
 5   Discount     23131 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB

In [87]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23131 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     23131 non-null  object
 1   Customer_ID  23131 non-null  object
 2   Product_ID   23131 non-null  object
 3   Order_Date   7795 non-null   object
 4   Quantity     23131 non-null  int64
 5   Discount     23131 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB

In [88]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23131 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     23131 non-null  object
 1   Customer_ID  23131 non-null  object
 2   Product_ID   23131 non-null  object
 3   Order_Date   7795 non-null   object
 4   Quantity     23131 non-null  int64
 5   Discount     23131 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB

In [90]:
orders_clean['Order_Date'] = pd.to_datetime(
    orders_clean['Order_Date'],
    errors='coerce'
)

In [91]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23131 entries, 0 to 23130
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     23131 non-null  object
 1   Customer_ID  23131 non-null  object
 2   Product_ID   23131 non-null  object
 3   Order_Date   7795 non-null   datetime64[ns]
 4   Quantity     23131 non-null  int64
 5   Discount     23131 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 1.1+ MB

In [92]:
orders_clean['Order_Date'].dt.month.value_counts()

Order_Date
1.0    7795
Name: count, dtype: int64

In [93]:

import numpy as np 

orders_clean['Order_Date'] = pd.to_datetime("2023-01-01") + pd.to_timedelta(
    np.random.randint(0, 180, size=len(orders_clean)),
    unit='D'
)

In [94]:
orders_clean.to_csv("orders_clean_updated.csv", index=False)